#type=test
#mid=mid_test
#test_ApiURL=https://tcash.settlebank.co.kr/pgtrans/CashReceiptMultiAction.do?_method=insertReceiptInfo

type=real
mid=mtouch
real_ApiURL=http://pgwas2:10034/cashReceipt/insert